### ISSUE TITLE
How to show scroll bar ?

### ISSUE THREAD

**Issue by crile** [joshavanier/log#45]
Hi, I see that it is possible to scroll nearly everywhere.
However, nothing in the GUI show me that I can do it.
Is there a way to show some scroll bar ?

Bonus question: Is there a way to scroll without the mouse ?

**Comment by joshavanier** [comment]
You should be able to scroll using a scrollwheel on a mouse or trackpad gestures on a laptop

**Comment by crile** [comment]
Thanks, but I mean without the scrollwheel.
Anyway, is there a way the show the scroll bar ?

**Comment by joshavanier** [comment]
Yeah but it may break the UI. You just need to delete this line: https://github.com/joshavanier/log/blob/d47e34a945a6f56e9a8d6ea339b8de80d4fd7415/src/css/macian.min.css#L39

**Comment by crile** [comment]
wow, thanks for the quick reply.
It works except for the Entries tab.
Thanks Again.

**Comment by Godje** [comment]
The scrolling may interfere with console typing.
Because you press UP in console to go back in history. At the same time if nothing is typed into console you press up and it scrolls up anywhere but in Entries. So if the scrolling buttons will be mentioned in the navigation part of the Guide, there has to be a different solution to scrolling.

**Comment by joshavanier** [comment]
I've added scrollbars in 1.0.5. They only appear when there's something to scroll hehe. Pardon the delay; I've had a busy semester
