### ISSUE TITLE
Generate log.desktop file

### ISSUE THREAD

**Issue by ahstro** [joshavanier/log#51]
https://wiki.archlinux.org/index.php/Desktop_entries

**Comment by Godje** [comment]
I bet this is not in consideration for Josh, (neither is for me), because
of i3wm. I run rofi, so that may be useful, but still, the Desktop entry
depends on the location of the file. And that also depends on how you
install Log. I downloaded Log from itch.io, while some people may install
it manually through building. That may affect the location of the link.

2018-05-11 5:09 GMT-07:00 Anton Strömkvist <notifications@github.com>:

**Comment by ahstro** [comment]
rofi is the exact reason why I want this. For now, I just hacked together a desktop entry for myself, but I've created a log-git package for Arch, and it'd be nice to be able to supply a desktop entry with that. If the desktop entry was simply generated in the build folder along with the rest of the files, it'd be a simple matter to just copy or link it to the correct destination if one wanted to.

**Comment by ahstro** [comment]
I put the executable in `/usr/bin`, which most Linux distros should probably do, so I guess `/usr/bin` for `Path` and `Log` for `Exec`?

**Comment by joshavanier** [comment]
Let me know if it works so I can close this issue

**Comment by ahstro** [comment]
Looks to work mostly fine, but check #52 :slightly_smiling_face:
