### ISSUE TITLE
[Bug] Uncaught TypeError: Cannot read property 'sp' of undefined

### ISSUE THREAD

**Issue by kmossco** [joshavanier/log#6]
When loading the app for the first time I am getting this error:

<img width="975" alt="image" src="https://user-images.githubusercontent.com/11810153/32304713-3a991c4e-bf69-11e7-82d8-af5a45709b08.png">

```
Uncaught TypeError: Cannot read property 'sp' of undefined @log.js:303 
```

The code that is having this issue:

```js
let ld = Log.data,
        sp = ld.sp,

        n = new Date(),
        y = new Date(n)
```

This blocks any input and can't use the app. I tried adding data to my log manually, but even after restarting this happened.

Versions:
Log@0.1.1
node v7.7.2
electron 1.7.9
Mac OS X 10.12.6

**Comment by joshavanier** [comment]
Oops. I do apologise for this inconvenience. `sp = ld.sp,` is actually redundant but does not seem to cause any errors in Linux (which is why I missed it). I will push an update to fix this when I'm done with my classes today. In the meantime, you may delete that line and try again.

Thank you for bringing this to my attention and have a nice day

**Comment by kmossco** [comment]
No need to apologize at all, thank you so much for open sourcing and sharing this with us. ✌️
